web:
  image: alexcheng/magento
  ports:
    - "80:80"
  links:
    - mysql
  env_file:
    - env
mysql:
  image: "mariadb:latest"
  volumes:
    - magentoDB:/var/lib/mysql
  env_file:
    - env
  environment:
    MYSQL_HOST: localhost
